apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.4.0
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            # Kafka Broker ID
            - name: KAFKA_BROKER_ID
              value: "1"

            # Enable KRaft mode without Zookeeper
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"

            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"

            # Configure listeners (PLAINTEXT for clients, CONTROLLER for KRaft)
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"

            # Map security protocols
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

            # Advertise Kafka listeners for external clients
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka.default.svc.cluster.local:9092"

            # Kafka cluster ID for KRaft mode
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: "qE9bI7rOTkKXGWN9PLv-Ew"

          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka

      volumes:
        - name: kafka-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka