server:
  port: 8080

database:
  host: postgres
  port: 5432
  user: postgres
  password: password
  dbname: orders

redis:
  host: redis
  port: 6379
  password: ""

kafka:
  brokers:
    - kafka:9092
  topic: order_events